latest_version = "3.3"

["3.3"]
title = "we added emotes to penis robot"
description = """
hey pp growers, we added a couple of commands u can use to interact with ur friends (if u have any <a:IFellDownToEarth:918952010517184524>)
‎ 
</bite:1492261240112812193> hope nobody gets hurt
</cry:1492262554100175000> when ur in TEARS and SOBBING :(
</facepalm:1492262554536513550> when something is so stupid u gotta facepalm
</hug:1492262554536513547> give someone a hug
</kiss:1492262554100175002> give someone a smooch
</pat:1492262554536513546> give someone a few pats
</poke:1492261240112812194> very VERY annoying
</wink:1492262554536513549> wink at someone
‎
we suspect middleschool e-couples will LOVE this update <:listening:897460719799382126>
Next update coming soon! (||Slavery update<a:eyesGoogly:906682242217181244>||)
‎ 
and as always, join [**discord.gg/ppbot**](https://discord.gg/ppbot) to hang out with fellow pp growers or the developers
‎ 
-# \\- schlöpp
"""

["3.2"]
title = "Server leaderboards!!"
description = """
hey pp growers, </leaderboard:1418285010451955872> now includes an option to view pps from **only the server you're in** :D
‎ 
you can now fight amongst your friends for the biggest pps in your server <:ppevil:871396299830861884>
‎ 
and as always, join [**discord.gg/ppbot**](https://discord.gg/ppbot) to hang out with fellow pp growers or the developers
‎ 
-# \\- schlöpp
"""

["3.1.2"]
title = "Christmas Event Over - HAPPY NEW YEAR!!"
description = """
Holiday season is over but the updates aren't. ||Lottery, slave labor and 1v1 fighting coming 2026:tm:||
"""

["3.1.1"]
title = "2025 CHRISTMAS UPDATE!"
description = """
ho ho ho its holiday season so we jolly-fied everything!!! <:pppog:871396409809698898> <a:CANDY_CANE:1452409272112513156>
‎ 
[**TRIPLE MULTIPLIER EVENT AND HUGE GIVEAWAY**](https://discord.gg/ppbot) **TO CELEBRATE THE HOLIDAYS!**
"""


["3.1"]
title = "Blackjack update!!!"
description = """
try it out now with `/casino` !!
-# christmas event coming soon :eyes:
‎ 
[**TRIPLE MULTIPLIER EVENT AND HUGE GIVEAWAY**](https://discord.gg/ppbot) **TO CELEBRATE THE NEW UPDATE!**"""

["2.0"]
title = "The pp bot revamp is complete"
description = """
- All commands will **run faster** and **look better**
- All commands have been reworked to be **user-friendly**
- **BRAND NEW** `/casino`
- **BRAND NEW MINIGAMES** FOR `/beg` `/fish` `/hunt`
- **LOWER COOLDOWNS** for [voters](https://top.gg/bot/735147633076863027/vote)
- And **SO MUCH MORE**

‎ 
[**TRIPLE MULTIPLIER EVENT AND HUGE GIVEAWAY**](https://discord.gg/ppbot) **TO CELEBRATE THE NEW UPDATE!**"""